//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class APO_PCO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APO_PCO()
        {
            this.USERS = new HashSet<USER>();
            this.ASSETS = new HashSet<ASSET>();
        }
    
        [Key]
        public long APO_PCO_PIV_BADGE_NUM { get; set; }
        public string USER_ID { get; set; }
        [ForeignKey("CENTER")]
        public string CENTER { get; set; }
        public Nullable<bool> CAR_ADMIN { get; set; }
        public Nullable<bool> CAN_SEND_REMINDER { get; set; }
        public Nullable<bool> MUST_CHANGE_PWD { get; set; }
        public Nullable<bool> ENABLED { get; set; }
        public string LAST_NAME { get; set; }
        public string MIDDLE_INITIAL { get; set; }
        public string FIRST_NAME { get; set; }
        public string PHONE_NUM { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD_REMINDER { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
        public string PASSWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSET> ASSETS { get; set; }
    }
}
