//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ASSET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSET()
        {
            this.USERS = new HashSet<USER>();
        }
    
        [Key]
        public int BARCODE { get; set; }
        public string MANUFACTURER { get; set; }
        public string MODEL { get; set; }
        public string SERIAL_NUM { get; set; }
        public string COMPUTER_NAME { get; set; }
        public Nullable<System.DateTime> DATETIME_ASSIGNED { get; set; }
        public Nullable<System.DateTime> DATETIME_RECEIVED { get; set; }
        public string STATE { get; set; }
        [ForeignKey("APO_PCO_PIV_BADGE_NUM")]
        public Nullable<long> APO_PCO_PIV_BADGE_NUM { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
    
        public virtual APO_PCO APO_PCO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERS { get; set; }
    }
}
