//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAREntities1 : DbContext
    {
        public CAREntities1()
            : base("name=CAREntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APO_PCO> APO_PCO { get; set; }
        public virtual DbSet<ASSET> ASSETS { get; set; }
        public virtual DbSet<CENTER> CENTERS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
