//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class USER
    {
        [Key]
        public long USER_PIV_BADGE_NUM { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string MIDDILE_INITIAL { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DATETIME_ACCEPTED { get; set; }
        [ForeignKey("BARCODE")]
        public Nullable<int> BARCODE { get; set; }
        [ForeignKey("APO_PCO_PIV_BADGE_NUM")]
        public Nullable<long> APO_PCO_PIV_BADGE_NUM { get; set; }
        public Nullable<int> PREVIOUS_BARCODE { get; set; }
        public Nullable<bool> OUTSTANDING_ASSET { get; set; }
        public Nullable<System.DateTime> LAST_REMINDER { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
    
        public virtual APO_PCO APO_PCO { get; set; }
        public virtual ASSET ASSET { get; set; }
    }
}
